# conteiners com dependencias pre-instaladas
FROM python:3.9
#versão
ADD rasc.py .
#arquivo dessa pasta
RUN pip install Flask
# roda esse comando
CMD ["python","./rasc.py"]
# usa o interpretador do python no arquivo python